version: 2

project_name: machinefile

before:
  hooks:
    - go mod tidy

builds:
  - id: machinefile
    main: ./cmd/machinefile
    binary: machinefile
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: binary
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

nfpms:
  - id: packages
    package_name: machinefile
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Ducttape Infra
    homepage: https://github.com/ducttape-infra/machinefile
    maintainer: Ducttape Infra <developers@ducttape-infra.org>
    description: |-
      Parse and execute Containerfile instructions on a host system.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/sbin
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/machinefile/LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
